language: java

jdk:
  - oraclejdk7
  - openjdk7
  - openjdk6

script:
  - mvn install:install-file -Dfile=sdk/go-plugin-api-current.jar -DgroupId=com.thoughtworks.go -DartifactId=go-plugin-api -Dversion=14.3.0 -Dpackaging=jar
  - mvn clean package
